##########################################################################
#               MAKEFILE INIT FOR MYODBC 3.51 TEST_LIBRARY               #
#                    (C) MySQL AB 1995-2006                              #
##########################################################################

#
# SPECIFY THE DSN, UID and PWD COMMAND LINE OPTIONS FOR 'TESTALL' NET
#

MYDSN      = test
MYUID      = 
MYPWD      = 

#	
# COMPILATION SPECIFICATION
# Mainly for WINDOWS, on UNIX it will be ovveritten in Makefile.am
# 

# MYSQL_DIR  = c:\\mysql
ODBC_DIR   = ../
INCLUDE    = -I. -I$(MYSQL_DIR)/include -I$(ODBC_DIR)/include
LIBDIR     = -L$(MYSQL_DIR)/lib/opt -L$(ODBC_DIR)/win32/Release/myodbc3.lib


