#!/bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_version 2.0

# Always add in the postinst, always delete in the prerm -- this way,
# we'll always have a good reference count in odbcinst.ini.
db_get libmyodbc/addtoodbc || true
if [ "$RET" = "true" ]; then
	odbcinst -i -d -f /usr/share/libmyodbc/odbcinst.ini 1>&2
fi

#DEBHELPER#
