#!/usr/bin/env bash

# Variables the installer application automatically passes along
# $0 : Returns the path to the script
# $1 : Returns the path to the package
# $2 : Returns the target location (for example: /Applications)
# $3 : Returns the target volume (for example: /Volumes/Macintosh HD)

#############
### Setup ###
#############
TARGET_VOLUME=$3
LOG_FILE="/tmp/postinstall_MongoDB_ODBC.log"

# Log an error
err(){
    
    echo "Err: $@" | tee -a $LOG_FILE
}

# Log an general info
info(){
    if [[ ! -e $LOG_FILE ]]; then
        touch $LOG_FILE
    fi
     echo "Info: $@" | tee -a $LOG_FILE
}

# Setup the log file
if [[ ! -e $LOG_FILE ]]; then
    # Create a new log file
    touch $LOG_FILE
else
    # Clean up the existing file
    > $LOG_FILE 
fi

ODBC_PATH="/Library/ODBC"
if [[ ! -z $TARGET_VOLUME ]]; then
    ODBC_PATH="$TARGET_VOLUME/Library/ODBC"
fi
INI="$ODBC_PATH/odbcinst.ini"
info "Drivers configuration will be added to $INI"
INSTALL_ROOT="/Library/MongoDB/ODBC/"
# Get the latest installed version
LATEST_VERSION=$(ls $INSTALL_ROOT/| grep -E "[0-9]\.[0-9]\.[0-9]" | sort | cut -d '/' -f2 | tail -n 1)
INSTALL_PATH=$INSTALL_ROOT$LATEST_VERSION
DRIVERS_SECTION="ODBC Drivers"
MDB_UNICODE="MongoDB Unicode ODBC $LATEST_VERSION"
MDB_ANSI="MongoDB ANSI ODBC $LATEST_VERSION"
MDB_UNICODE_DRIVERS="$INSTALL_PATH/libmdbodbcw.so"
MDB_ANSI_DRIVERS="$INSTALL_PATH/libmdbodbca.so"
CREATED_NEW_INI_FILE=0
MDB_UNICODE_DRIVER_INSTALLED=0
MDB_ANSI_DRIVER_INSTALLED=0
MDB_UNICODE_DRIVER_CONFIGURED=0
MDB_ANSI_DRIVER_CONFIGURED=0

# Flag the driver as installed if not already done
flagDriversAsInstalled(){
        if [ $MDB_UNICODE_DRIVER_INSTALLED == 0 ]; then
            echo "$MDB_UNICODE = Installed" >> $INI
            MDB_UNICODE_DRIVER_INSTALLED=1
        fi
        if [ $MDB_ANSI_DRIVER_INSTALLED == 0 ]; then
            echo "$MDB_ANSI = Installed" >> $INI
            MDB_ANSI_DRIVER_INSTALLED=1
        fi
}

#############################################################
### Configure the newly installed drivers in odbcinst.ini ###
#############################################################
# Create the ODBC directory if it doesn't exist already
if [[ ! -e $ODBC_PATH ]]; then
    info "Creating $ODBC_PATH directory"
    mkdir -p $ODBC_PATH
elif [[ ! -d $ODBC_PATH ]]; then
     err "$ODBC_PATH already exists but is not a directory"
     exit 1   
fi

#Update the odbcinst.ini with the latest driver path and mark it as installed
if [[ ! -e $INI ]]; then
    info "$INI does not exists, creating"
    touch $INI
    echo "[ODBC Drivers]" >> $INI
    echo "$MDB_UNICODE = Installed" >> $INI
    echo "$MDB_ANSI = Installed" >> $INI
    echo "" >> $INI
    echo "[$MDB_UNICODE]" >> $INI
    echo "Driver = $MDB_UNICODE_DRIVERS" >> $INI
    echo "" >> $INI
    echo "[$MDB_ANSI]" >> $INI
    echo "Driver = $MDB_ANSI_DRIVERS" >> $INI
    $CREATED_NEW_INI_FILE=1
fi

#If there was an existing odbcinst file, update the odbcinst.ini
# with the latest driver path
if [[ $CREATED_NEW_INI_FILE == 0 ]]; then
    BACK_INI="$INI.back"
    info "Back up file $BACK_INI"
    ODBC_DRIVERS_SECTION_EXISTS=0
    CURRENT_SECTION="NONE"
    PREVIOUS_SECTION="NONE"

    # Make a copy of the existing ini file
    cp $INI $BACK_INI
    if [[ -e $BACK_INI ]]; then
        # Clear the INI file
        > $INI

        # Read the backup odbcinst.ini.back file and recreate the new updated odbcinst.ini one
        while IFS= read -r line
        do
            if [[ "$line" =~ ^\[.*\]$ ]]; then
                PREVIOUS_SECTION=$CURRENT_SECTION
                # Found a section
                if grep -iqF "[ODBC Drivers]" <<< "$line"; then
                    # Found the [ODBC Drivers] section 
                    # where all drivers are listed
                    ODBC_DRIVERS_SECTION_EXISTS=1
                    CURRENT_SECTION="ODBC"
                elif grep -iqF "[$MDB_UNICODE]" <<< "$line"; then
                    # Found the [MongoDB Unicode ODBC {version}] section
                    CURRENT_SECTION="UNICODE"
                elif grep -iqF "[$MDB_ANSI]" <<< "$line"; then
                    # Found the [MongoDB ANSI ODBC {version}] section
                    CURRENT_SECTION="ANSI"
                else
                    CURRENT_SECTION="OTHER"
                fi

                # Found a new section right after [ODBC Drivers]
                # Need to add the drivers lines in [ODBC Drivers] section
                if [ $PREVIOUS_SECTION == "ODBC" ]; then
                    flagDriversAsInstalled
                    echo "" >> $INI
                fi
                echo "$line" >> $INI
            else
                if [ $CURRENT_SECTION == "ODBC" ]  && grep -iqF "$MDB_UNICODE" <<< "$line" ; then
                    # Found the latest unicode MongoDB driver already configured
                    # Make sure to mark it "Installed"
                    echo "$MDB_UNICODE = Installed" >> $INI
                    MDB_UNICODE_DRIVER_INSTALLED=1
                elif [ $CURRENT_SECTION == "ODBC" ] && grep -iqF "$MDB_ANSI" <<< "$line" ; then
                    # Found the latest ANSI MongoDB driver already configured
                    # Make sure to mark it "Installed"
                    echo "$MDB_ANSI = Installed" >> $INI
                    MDB_ANSI_DRIVER_INSTALLED=1
                elif [ $CURRENT_SECTION == "UNICODE" ] && grep -iqF "Driver" <<< "$line" ; then
                    # Make sure the driver install path is correct
                    echo "Driver = $MDB_UNICODE_DRIVERS" >> $INI
                    MDB_UNICODE_DRIVER_CONFIGURED=1
                elif [ $CURRENT_SECTION == "ANSI" ] && grep -iqF "Driver" <<< "$line" ; then
                    # Make sure the driver install path is correct
                    echo "Driver = $MDB_ANSI_DRIVERS" >> $INI
                    MDB_ANSI_DRIVER_CONFIGURED=1
                else
                    echo "$line" >> $INI
                fi        
            fi
        done < "$BACK_INI"

        # Reached the end of the file, if [ODBC Drivers] was the last section, 
        # then add the lines for each MongoDB drivers
        flagDriversAsInstalled

        # Configure the driver if needed by adding their respective sections at the end of the odbcinst.ini file
        if [ $MDB_UNICODE_DRIVER_CONFIGURED == 0 ]; then
            echo "" >> $INI
            echo "[$MDB_UNICODE]" >> $INI
            echo "Driver = $MDB_UNICODE_DRIVERS" >> $INI
        fi
        if [ $MDB_ANSI_DRIVER_CONFIGURED == 0 ]; then
            echo "" >> $INI
            echo "[$MDB_ANSI]" >> $INI
            echo "Driver = $MDB_ANSI_DRIVERS" >> $INI
        fi

        # No [ODBC Drivers] section existed in the file, adding one at the beginning of the file
        if [ $ODBC_DRIVERS_SECTION_EXISTS == 0 ]; then
            sed -i -e "1s/^/\[ODBC Drivers\]\\n$MDB_UNICODE = Installed\\n$MDB_ANSI = Installed\\n\\n/g" $INI
        fi
    else
        err "An error occured while making a backup of the existing odbcinst.ini file"
        exit 1
    fi
fi

# Done, everything went well
info "postinstall script was successful"
exit 0
