#! /bin/sh
set -e

# Run individual MyODBC test samples

# By defauly, it uses the DSN=myodb3; you can ovveride this
# by supplying the command line options to the sample

./my_basics
./my_connect
./my_param
./my_result
./my_cursor
./my_tran



